# Tree names (input files in format <tree_name>.fa)
treeNames:
  - Combined_OG_MPA
  - OG0001988_MPA
  - OG0021415_YqhA

# Set to TRUE to use only species under speciesNames, or FALSE to use all species in original
selectSpecies: 'FALSE'

# Species names (exactly as written in gene names in fasta file)
speciesNames:
  - Zmays
  - Sbicolor
  - Sviridis
  - Pvirgatum
  - Osativa
  - Bdistachyon
  - Spolyrhiza
  - Slycopersicum
  - Mguttatus
  - Gmax
  - Athaliana
  - Brapa
  - Atrichopoda
  - Smoellendorffii
  - Ppatens
  - Mpolymorpha
  - Creinhardtii
  - Scerevisiae
  - Escherichia_coli
  - Rhizobium_leguminosarum
  - Corynebacterium_glutamicum
  - Bacillus_subtilis
  - Campylobacter_jejuni
  - Neisseria_meningitidis
  - Nostoc_sp
